image: docker:stable
stages:
  - build
  - deploy

build: 
  stage: build
  services: 
    - docker:dind
  script:
    - docker info
    - docker build -t 7744149944/ffm-auth .
    - echo "$PASSWORD" | docker login -u "$USER" --password-stdin
    - docker push 7744149944/ffm-auth
deploy:
  stage: deploy
  services: 
    - docker:dind
  image: ictu/sshpass
  script: 
    - sshpass -p 12345 ssh -o StrictHostKeyChecking=no ubuntu@18.216.171.201 "cd project-transformation-ffm-auth && docker-compose down && docker-compose up -d"
